### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by muhsinciftci** [mboeck11/BGVAR#13]
Hi, I am trying to execute the BGVAR for more than 50 countries and at some point I keep getting a problem when  stacking the estimated country models. The error I get is below.  The interesting point is that when I set the number of draws to 1000, it does work but setting it to 5000 prompts the error.  I thought that this could be due to the RAM (storage), but when I run the example model given in the vignette, it seems to work. What am I missing? Any help would really be appreciated. By the way, I am using MacOs with 4 cores + Intel Processor + 8GB RAM.
"
Estimation of country models starts...
Estimation done and took 4 mins 41 seconds.
Start stacking: 
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|

Stacking finished.
Computation of BGVAR yields 0 (0%) draws (active trimming).Error in l$post : $ operator is invalid for atomic vectors
In addition: Warning message:
In parallel::mclapply(X, FUN, ..., mc.cores = cores) :
  all scheduled cores encountered errors in user code
"

**Comment by mboeck11** [comment]
Hi,

It seems that BGVAR doesn't find any draws that fulfill the trimming argument. Have you changed the ``eigen`` argument? Do you find draws when you compute the model with 1000 instead of 5000 draws, not changing any of the other specifications? If you have changed the value of ``eigen``, to which value?

I should built in a specific error message for this case, thanks for pointing this out.

Best,
Max
