### ISSUE TITLE
More flexibility in model specification

### ISSUE THREAD

**Issue by devproglab** [mboeck11/BGVAR#27]
Hi! First I wanted to thank for a one of a kind package which is the only alternative to working with GVAR models in Matlab. I was wondering if it is possible to include the following features which would enhance the flexibility of model specification:

- Different number of lags for endogenous, weakly exogenous and global variables in country models. As of now, if I understand correctly, `plags` governs all of them
- A possibility to exclude some variables from being included as weakly exogenous, so thatcountry models could, e.g., include trade-weighted output of other countries but not their level of unemployment/government spending (determined endogenously in each country's model)
- A more flexible specification of the 'dominant unit' models allowing to exclude certain weakly exogenous variables from certain equations. E.g., I have a subnational model (regions of a single country) + dominant unit model with oil prices, policy rate and government spending. In this setting I would want the policy rate and government spending to weighted regional economic activity and inflation, but that would be undesirable for the price of oil which is determined in the global market.

As far as I know, some of these features are implemented in the GVAR Toolbox, but it would be really nice to have them here.

**Comment by mboeck11** [comment]
Hi,

Thanks a lot! Great that the package is of use. I think that most of these features are already implemented in BGVAR as follows:

- lags: You can specify different number of lags for endogenous and weakly exogenous variables. Just provide a vector of length two instead of one. I copy & paste the description from the reference manual below. Regarding global/exogenous variables: Those can be added via `Ex`. If you want to have lags of those as well, just provide them directly. I think this is more flexible than automatically lagging global exogenous variables - often you just want to control for some global stuff contemporaneously.
- If you want to exclude some variables from being included as weakly exogenous, that is also already possible. Via the `expert` settings you can specify `Wex.restr`. That should do exactly what you are asking for.
- The dominant unit specificaion can be achieved as follows. Via the `expert` settings, you can specify an `other entity` in BGVAR. This model can have a global variable (e.g., oil prices) and some weakly exogenous variables from all the other country models (e.g., weighted averages from regional economic activity and inflation as you're referring to). You can also specify different weights for this entity.

In the [vignette](https://cran.r-project.org/web/packages/BGVAR/vignettes/examples.html), we cover these special cases. I hope this is helpful otherwise I am happy to help. If something is unclear, just let me know.

All the best!

From the reference manual of bgvar():
`plag: Number of lags used. Either a single value for domestic and weakly exogenous,
or a vector of length two. Default set to plag=1.`

`expert: Expert settings, must be provided as list. Default is set to NULL.`

`Wex.restr: Character vector containing variables that should be excluded from being used as weakly exogenous from all unit models. An example that has often been used in the literature is to place these restrictions on nominal exchange rates. Default is NULL in which case all weakly exogenous variables are treated symmetrically.`

`OE.weights: Default value is set to NULL. Can be used to provide information of how to handle additional country models (other entities). Additional country models can be used to endogenously determine variables that are (weakly) exogenous for the majority of the other country models. As examples, one could think of an additional oil price model (see also Mohaddes and Raissi 2019) or a model for the joint euro area monetary policy (see also Georgiadis 2015; Feldkircher, Gruber and Huber (2020)). The data for these additional country models has to be contained in Data. The number of
additional country models is unlimited. Each list entry of OE.weights has to be named similar to the name of the additional country model contained in Data. Each slot of OE.weight has to contain the following information: weights, variables, exo.`

**Comment by devproglab** [comment]
Thanks, your points cover most of my requirements! I must have missed some of these details in the vignette.
