### ISSUE TITLE
Feature request: allow for different lag order depending on the type of variable

### ISSUE THREAD

**Issue by danfer21** [mboeck11/BGVAR#8]
Hello,

It would be very useful if the user of BGVAR could select the lag order for each of the types of variables that enter into the model (i.e. endogenous, weakly exogenous, and exogenous).

Thank you!

**Comment by mboeck11** [comment]
Hi,

you can no either provide plag of length one or two. Length one specifies the same lag order for both endogenous and weakly exogenous variables. However, if specified with length two, you can now distinguish between the lag order on the endogenous and weakly exogenous part.

Note that you can not specify the lag order of the truly exogenous variables (given in Ex), because of its more general structure. There you could also have potentially variables which you do not want to have lagged in your specification. Hence, you would have to provide your own data matrix with already lagged values in it.

I hope this helps!

Best,
Max
